"""TOTP two-factor authentication (RFC 6238) with single-use recovery codes.

* Secrets are 160-bit base32 strings generated by pyotp.
* A code is accepted for the current 30 s step and one step either side
  (clock drift), but never for a step at or before the last accepted one,
  so an observed code cannot be replayed.
* Recovery codes are random (~62 bits), shown once, stored as SHA-256 hashes
  and consumed on use. A fast hash is sufficient because the codes are
  high-entropy random strings, not user-chosen passwords.
* After MAX_FAILED_ATTEMPTS wrong codes the account's second factor is
  locked for LOCKOUT, on top of the per-IP request rate limit.
"""

import hashlib
import hmac
import secrets
from datetime import datetime, timedelta, timezone

import pyotp
import segno
from fastapi import HTTPException
from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.user import RecoveryCode, User

RECOVERY_CODE_COUNT = 10
MAX_FAILED_ATTEMPTS = 5
LOCKOUT = timedelta(minutes=15)
VALID_WINDOW = 1  # steps accepted either side of "now"

_RECOVERY_ALPHABET = "abcdefghjkmnpqrstuvwxyz23456789"  # no 0/o, 1/l/i


def new_secret() -> str:
    return pyotp.random_base32()


def provisioning_uri(secret: str, email: str) -> str:
    return pyotp.TOTP(secret).provisioning_uri(name=email, issuer_name=settings.app_name)


def qr_svg_data_uri(uri: str) -> str:
    return segno.make(uri, micro=False).svg_data_uri(scale=5, border=2)


def _hash_recovery_code(code: str) -> str:
    normalized = code.strip().lower().replace("-", "").replace(" ", "")
    return hashlib.sha256(normalized.encode()).hexdigest()


def _new_recovery_code() -> str:
    raw = "".join(secrets.choice(_RECOVERY_ALPHABET) for _ in range(12))
    return f"{raw[:4]}-{raw[4:8]}-{raw[8:]}"


def match_totp(secret: str, code: str, last_used_step: int | None) -> int | None:
    """Return the matched time step, or None. Pure function, easy to test."""
    code = code.strip()
    if len(code) != 6 or not code.isdigit():
        return None
    totp = pyotp.TOTP(secret)
    current = totp.timecode(datetime.now(timezone.utc))
    for step in range(current - VALID_WINDOW, current + VALID_WINDOW + 1):
        if last_used_step is not None and step <= last_used_step:
            continue
        if hmac.compare_digest(totp.generate_otp(step), code):
            return step
    return None


async def delete_recovery_codes(db: AsyncSession, user: User) -> None:
    await db.execute(delete(RecoveryCode).where(RecoveryCode.user_id == user.id))


async def replace_recovery_codes(db: AsyncSession, user: User) -> list[str]:
    """Invalidate all existing recovery codes and return a fresh set (plaintext)."""
    await delete_recovery_codes(db, user)
    codes = [_new_recovery_code() for _ in range(RECOVERY_CODE_COUNT)]
    db.add_all(RecoveryCode(user_id=user.id, code_hash=_hash_recovery_code(c)) for c in codes)
    return codes


async def count_unused_recovery_codes(db: AsyncSession, user: User) -> int:
    result = await db.execute(
        select(RecoveryCode.id).where(
            RecoveryCode.user_id == user.id, RecoveryCode.used_at.is_(None)
        )
    )
    return len(result.all())


async def _consume_recovery_code(db: AsyncSession, user: User, code: str) -> bool:
    result = await db.execute(
        select(RecoveryCode).where(
            RecoveryCode.user_id == user.id,
            RecoveryCode.code_hash == _hash_recovery_code(code),
            RecoveryCode.used_at.is_(None),
        )
    )
    row = result.scalars().first()
    if row is None:
        return False
    row.used_at = datetime.now(timezone.utc)
    return True


def _as_aware(value: datetime) -> datetime:
    # SQLite (tests) hands back naive datetimes; PostgreSQL returns aware ones.
    return value if value.tzinfo else value.replace(tzinfo=timezone.utc)


async def check_second_factor(
    db: AsyncSession, user: User, code: str, *, allow_recovery: bool = True,
) -> None:
    """Verify a TOTP or recovery code for ``user`` or raise.

    Commits the session in every outcome so that the failure counter, the
    replay marker and consumed recovery codes are persisted.
    """
    now = datetime.now(timezone.utc)
    if user.totp_locked_until and _as_aware(user.totp_locked_until) > now:
        raise HTTPException(
            status_code=429,
            detail="Too many invalid codes. Try again later.",
            headers={"Retry-After": str(int(LOCKOUT.total_seconds()))},
        )
    if not user.totp_secret:
        raise HTTPException(status_code=400, detail="Two-factor authentication is not set up.")

    step = match_totp(user.totp_secret, code, user.totp_last_used_step)
    ok = step is not None
    if ok:
        user.totp_last_used_step = step
    elif allow_recovery:
        ok = await _consume_recovery_code(db, user, code)

    if ok:
        user.totp_failed_attempts = 0
        user.totp_locked_until = None
        await db.commit()
        return

    user.totp_failed_attempts += 1
    if user.totp_failed_attempts >= MAX_FAILED_ATTEMPTS:
        user.totp_failed_attempts = 0
        user.totp_locked_until = now + LOCKOUT
    await db.commit()
    raise HTTPException(status_code=401, detail="Invalid verification code.")
